version: "3.9"
services:
  counter-db:
    container_name: counter-db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=counter-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
